version: "3.9"
    
services:
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    volumes:
      - db_data:/var/lib/influxdb
      - "./influxdb.conf:/etc/influxdb/influxdb.conf:ro"
 
  grafana:
    depends_on:
      - influxdb
      - broker
    image: grafana/grafana
    ports:
      - "80:3000"
    volumes:
      - grafana_data:/var/lib/grafana

  broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro"

  telegraf:
    depends_on:
      - broker
      - influxdb
    image: telegraf
    volumes:
      - "./telegraf.conf:/etc/telegraf/telegraf.conf:ro"

volumes:
  db_data: {}
  grafana_data: {}

networks:
  default:
    name: powerbaas
